#ifndef NETWORK_MESSAGE_TYPES_H_
#define NETWORK_MESSAGE_TYPES_H_

enum NetworkMessageType 
{
	BA_TEST_MESSAGE,
	BA_MOVE_FORWARD,
	BA_MOVE_BACK,
	BA_MOVE_LEFT,
	BA_MOVE_RIGHT,
	BA_MOVE_BY_VEC,
	BA_SHOOT_LEFT,
	BA_SHOOT_RIGHT
};

#endif //NETWORK_MESSAGE_TYPES_H_
